image: marcoturi/ionic:latest

stages:
  - test
  - deploy

before_script:
  - npm i -g yarn --cache-min 999999999
  - yarn
  - gem install scss_lint
  - export DISPLAY=:99
  - npm run post-install

cache:
  paths:
    - yarn-cache/

build_web:
  stage: test
  only:
      - master
  script:
    - npm run lint
    - npm run scss-lint
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
    - npm run test
    - npm run build
    - npm run e2e

build_ios:
  stage: deploy
  only:
    - release
  script:
    - ./sh/ionic-login.sh
    - ls
    - npm run ios:release:ci
    - ./sh/ionic-package-ios.sh

build_android:
  stage: deploy
  only:
    - release
  script:
    - ls
    - npm run android:release
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk/
